const DB_KEY = 'doctor-appointment-local-db';

const seedDb = () => ({
  users: [
    {
      id: 'doctor-1',
      role: 'doctor',
      firstName: 'Amina',
      lastName: 'Rahman',
      email: 'doctor@example.com',
      phone: '01000000001',
      specialization: 'Cardiology',
      verified: true,
    },
    {
      id: 'doctor-2',
      role: 'doctor',
      firstName: 'Sadia',
      lastName: 'Khan',
      email: 'sadia.khan@example.com',
      phone: '01000000003',
      specialization: 'Dermatology',
      verified: true,
    },
    {
      id: 'doctor-3',
      role: 'doctor',
      firstName: 'Rafiq',
      lastName: 'Hossain',
      email: 'rafiq.hossain@example.com',
      phone: '01000000004',
      specialization: 'Pediatrics',
      verified: true,
    },
    {
      id: 'doctor-4',
      role: 'doctor',
      firstName: 'Nusrat',
      lastName: 'Jahan',
      email: 'nusrat.jahan@example.com',
      phone: '01000000005',
      specialization: 'Orthopedics',
      verified: true,
    },
    {
      id: 'doctor-5',
      role: 'doctor',
      firstName: 'Tanvir',
      lastName: 'Ahmed',
      email: 'tanvir.ahmed@example.com',
      phone: '01000000006',
      specialization: 'Neurology',
      verified: true,
    },
    {
      id: 'doctor-6',
      role: 'doctor',
      firstName: 'Mim',
      lastName: 'Akter',
      email: 'mim.akter@example.com',
      phone: '01000000007',
      specialization: 'Gynecology',
      verified: true,
    },
    {
      id: 'doctor-7',
      role: 'doctor',
      firstName: 'Imran',
      lastName: 'Chowdhury',
      email: 'imran.chowdhury@example.com',
      phone: '01000000008',
      specialization: 'ENT',
      verified: true,
    },
    {
      id: 'doctor-8',
      role: 'doctor',
      firstName: 'Farzana',
      lastName: 'Sultana',
      email: 'farzana.sultana@example.com',
      phone: '01000000009',
      specialization: 'Psychiatry',
      verified: true,
    },
    {
      id: 'patient-1',
      role: 'patient',
      firstName: 'John',
      lastName: 'Doe',
      email: 'patient@example.com',
      mobile: '01000000002',
    },
    {
      id: 'patient-2',
      role: 'patient',
      firstName: 'Sara',
      lastName: 'Ali',
      email: 'sara.ali@example.com',
      mobile: '01000000012',
    },
    {
      id: 'patient-3',
      role: 'patient',
      firstName: 'Rimon',
      lastName: 'Das',
      email: 'rimon.das@example.com',
      mobile: '01000000013',
    },
    {
      id: 'patient-4',
      role: 'patient',
      firstName: 'Naila',
      lastName: 'Islam',
      email: 'naila.islam@example.com',
      mobile: '01000000014',
    },
    {
      id: 'patient-5',
      role: 'patient',
      firstName: 'Tanim',
      lastName: 'Haque',
      email: 'tanim.haque@example.com',
      mobile: '01000000015',
    },
    {
      id: 'admin-1',
      role: 'admin',
      firstName: 'System',
      lastName: 'Admin',
      email: 'admin@example.com',
      isDemo: true,
    },
  ],
  doctors: [
    {
      id: 'doctor-1',
      firstName: 'Amina',
      lastName: 'Rahman',
      email: 'amina.rahman@gmail.com',
      phone: '01000000001',
      specialization: 'Cardiology',
      degree: 'MBBS, MD',
      experience: '8 years',
      clinicName: 'City Heart Center',
      city: 'Dhaka',
      state: 'Dhaka',
      country: 'INDIA',
      verified: true,
      price: '1200',
      services: 'Consultation, ECG, Follow-up',
    },
    {
      id: 'doctor-2',
      firstName: 'Sadia',
      lastName: 'Khan',
      email: 'sadia.khan@example.com',
      phone: '01000000003',
      specialization: 'Dermatology',
      degree: 'MBBS, DDV',
      experience: '6 years',
      clinicName: 'Skin Care Hub',
      city: 'Chattogram',
      state: 'Chattogram',
      country: 'INDIA',
      verified: true,
      price: '900',
      services: 'Skin consultation, Acne treatment, Allergy care',
    },
    {
      id: 'doctor-3',
      firstName: 'Rafiq',
      lastName: 'Hossain',
      email: 'rafiq.hossain@example.com',
      phone: '01000000004',
      specialization: 'Pediatrics',
      degree: 'MBBS, MD',
      experience: '10 years',
      clinicName: 'Little Care Clinic',
      city: 'Dhaka',
      state: 'Dhaka',
      country: 'INDIA',
      verified: true,
      price: '1100',
      services: 'Child health, Vaccination, Growth check',
    },
    {
      id: 'doctor-4',
      firstName: 'Nusrat',
      lastName: 'Jahan',
      email: 'nusrat.jahan@example.com',
      phone: '01000000005',
      specialization: 'Orthopedics',
      degree: 'MBBS, MS Ortho',
      experience: '9 years',
      clinicName: 'Bone & Joint Center',
      city: 'Sylhet',
      state: 'Sylhet',
      country: 'INDIA',
      verified: true,
      price: '1500',
      services: 'Fracture care, Joint pain, Sports injury',
    },
    {
      id: 'doctor-5',
      firstName: 'Tanvir',
      lastName: 'Ahmed',
      email: 'tanvir.ahmed@example.com',
      phone: '01000000006',
      specialization: 'Neurology',
      degree: 'MBBS, MD Neurology',
      experience: '12 years',
      clinicName: 'Brain & Spine Center',
      city: 'Dhaka',
      state: 'Dhaka',
      country: 'INDIA',
      verified: true,
      price: '2000',
      services: 'Headache, Migraine, Nerve disorder',
    },
    {
      id: 'doctor-6',
      firstName: 'Mim',
      lastName: 'Akter',
      email: 'mim.akter@example.com',
      phone: '01000000007',
      specialization: 'Gynecology',
      degree: 'MBBS, FCPS',
      experience: '7 years',
      clinicName: 'Women Care Center',
      city: 'Khulna',
      state: 'Khulna',
      country: 'INDIA',
      verified: true,
      price: '1300',
      services: 'Pregnancy care, Menstrual health, PCOS',
    },
    {
      id: 'doctor-7',
      firstName: 'Imran',
      lastName: 'Chowdhury',
      email: 'imran.chowdhury@example.com',
      phone: '01000000008',
      specialization: 'ENT',
      degree: 'MBBS, MS ENT',
      experience: '8 years',
      clinicName: 'Ear Nose Throat Clinic',
      city: 'Rajshahi',
      state: 'Rajshahi',
      country: 'INDIA',
      verified: true,
      price: '1000',
      services: 'Ear pain, Sinus, Throat infection',
    },
    {
      id: 'doctor-8',
      firstName: 'Farzana',
      lastName: 'Sultana',
      email: 'farzana.sultana@example.com',
      phone: '01000000009',
      specialization: 'Psychiatry',
      degree: 'MBBS, MD Psychiatry',
      experience: '11 years',
      clinicName: 'Mind Care Clinic',
      city: 'Barishal',
      state: 'Barishal',
      country: 'INDIA',
      verified: true,
      price: '1400',
      services: 'Anxiety, Stress, Sleep disorder',
    },
  ],
  patients: [
    {
      id: 'patient-1',
      firstName: 'John',
      lastName: 'Doe',
      email: 'patient@example.com',
      mobile: '01000000002',
      city: 'Dhaka',
      country: 'INDIA',
      gender: 'male',
    },
    {
      id: 'patient-2',
      firstName: 'Sara',
      lastName: 'Ali',
      email: 'sara.ali@example.com',
      mobile: '01000000012',
      city: 'Chattogram',
      country: 'INDIA',
      gender: 'female',
    },
    {
      id: 'patient-3',
      firstName: 'Rimon',
      lastName: 'Das',
      email: 'rimon.das@example.com',
      mobile: '01000000013',
      city: 'Dhaka',
      country: 'INDIA',
      gender: 'male',
    },
    {
      id: 'patient-4',
      firstName: 'Naila',
      lastName: 'Islam',
      email: 'naila.islam@example.com',
      mobile: '01000000014',
      city: 'Sylhet',
      country: 'INDIA',
      gender: 'female',
    },
    {
      id: 'patient-5',
      firstName: 'Tanim',
      lastName: 'Haque',
      email: 'tanim.haque@example.com',
      mobile: '01000000015',
      city: 'Khulna',
      country: 'INDIA',
      gender: 'male',
    },
  ],
  blogs: [
    {
      id: 'blog-1',
      title: 'Stay hydrated',
      description: 'Drink enough water every day.',
      createdAt: new Date().toISOString(),
      authorName: 'Amina Rahman',
    },
  ],
  appointments: [
    {
      id: 'appointment-1',
      trackingId: 'TRK-1001',
      patientId: 'patient-1',
      doctorId: 'doctor-1',
      firstName: 'John',
      lastName: 'Doe',
      email: 'patient@example.com',
      phone: '01000000002',
      status: 'pending',
      paymentStatus: 'unpaid',
      scheduleDate: '2026-05-05',
      scheduleTime: '10:00 AM',
      reasonForVisit: 'General checkup',
      patientType: 'patient',
    },
    {
      id: 'appointment-2',
      trackingId: 'TRK-1002',
      patientId: 'patient-2',
      doctorId: 'doctor-2',
      firstName: 'Sara',
      lastName: 'Ali',
      email: 'sara.ali@example.com',
      phone: '01000000012',
      status: 'scheduled',
      paymentStatus: 'paid',
      scheduleDate: '2026-05-08',
      scheduleTime: '11:00 AM',
      reasonForVisit: 'Skin rash',
      patientType: 'patient',
    },
    {
      id: 'appointment-3',
      trackingId: 'TRK-1003',
      patientId: 'patient-3',
      doctorId: 'doctor-3',
      firstName: 'Rimon',
      lastName: 'Das',
      email: 'rimon.das@example.com',
      phone: '01000000013',
      status: 'pending',
      paymentStatus: 'unpaid',
      scheduleDate: '2026-05-10',
      scheduleTime: '02:00 PM',
      reasonForVisit: 'Child care',
      patientType: 'patient',
    },
    {
      id: 'appointment-4',
      trackingId: 'TRK-1004',
      patientId: 'patient-4',
      doctorId: 'doctor-4',
      firstName: 'Naila',
      lastName: 'Islam',
      email: 'naila.islam@example.com',
      phone: '01000000014',
      status: 'scheduled',
      paymentStatus: 'paid',
      scheduleDate: '2026-05-12',
      scheduleTime: '01:00 PM',
      reasonForVisit: 'Knee pain',
      patientType: 'patient',
    },
    {
      id: 'appointment-5',
      trackingId: 'TRK-1005',
      patientId: 'patient-5',
      doctorId: 'doctor-5',
      firstName: 'Tanim',
      lastName: 'Haque',
      email: 'tanim.haque@example.com',
      phone: '01000000015',
      status: 'pending',
      paymentStatus: 'unpaid',
      scheduleDate: '2026-05-15',
      scheduleTime: '03:30 PM',
      reasonForVisit: 'Migraine',
      patientType: 'patient',
    },
  ],
  reviews: [
    {
      id: 'review-1',
      doctorId: 'doctor-1',
      patientId: 'patient-1',
      description: 'Very helpful and kind.',
      star: '5',
      isRecommended: true,
      response: '',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'review-2',
      doctorId: 'doctor-2',
      patientId: 'patient-1',
      description: 'Great dermatologist and very attentive.',
      star: '5',
      isRecommended: true,
      response: '',
      createdAt: new Date().toISOString(),
    },
  ],
  favourites: [],
  prescriptions: [],
  timeSlots: [
    {
      id: 'timeslot-1',
      doctorId: 'doctor-1',
      day: 'Monday',
      startTime: '09:00 AM',
      endTime: '01:00 PM',
      isBooked: false,
    },
    {
      id: 'timeslot-2',
      doctorId: 'doctor-2',
      day: 'Tuesday',
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      isBooked: false,
    },
    {
      id: 'timeslot-3',
      doctorId: 'doctor-3',
      day: 'Wednesday',
      startTime: '09:30 AM',
      endTime: '01:30 PM',
      isBooked: false,
    },
  ],
  medicines: [],
  contacts: [],
});

const isBrowser = typeof window !== 'undefined';

const mergeUniqueById = (existing = [], seed = []) => {
  const map = new Map();
  [...seed, ...existing].forEach((item) => {
    if (item?.id) {
      map.set(item.id, item);
    }
  });
  return Array.from(map.values());
};

const migrateDb = (db) => {
  const seed = seedDb();
  return {
    ...seed,
    ...db,
    users: mergeUniqueById(db?.users, seed.users),
    doctors: mergeUniqueById(db?.doctors, seed.doctors),
    patients: mergeUniqueById(db?.patients, seed.patients),
    blogs: mergeUniqueById(db?.blogs, seed.blogs),
    appointments: mergeUniqueById(db?.appointments, seed.appointments),
    reviews: mergeUniqueById(db?.reviews, seed.reviews),
    favourites: mergeUniqueById(db?.favourites, seed.favourites),
    prescriptions: mergeUniqueById(db?.prescriptions, seed.prescriptions),
    timeSlots: mergeUniqueById(db?.timeSlots, seed.timeSlots),
    medicines: mergeUniqueById(db?.medicines, seed.medicines),
    contacts: mergeUniqueById(db?.contacts, seed.contacts),
  };
};

export const getLocalDb = () => {
  if (!isBrowser) return seedDb();
  const raw = localStorage.getItem(DB_KEY);
  if (!raw) {
    const seeded = seedDb();
    localStorage.setItem(DB_KEY, JSON.stringify(seeded));
    return seeded;
  }
  try {
    const parsed = JSON.parse(raw);
    const migrated = migrateDb(parsed);
    if (JSON.stringify(parsed) !== JSON.stringify(migrated)) {
      localStorage.setItem(DB_KEY, JSON.stringify(migrated));
    }
    return migrated;
  } catch {
    const seeded = seedDb();
    localStorage.setItem(DB_KEY, JSON.stringify(seeded));
    return seeded;
  }
};

export const setLocalDb = (db) => {
  if (!isBrowser) return db;
  localStorage.setItem(DB_KEY, JSON.stringify(db));
  return db;
};

export const updateLocalDb = (updater) => {
  const db = getLocalDb();
  const next = updater(structuredClone(db));
  return setLocalDb(next || db);
};

export const makeId = (prefix) => `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
